#!/bin/bash
# job takes at most 0 days, 0 hours, 10 minutes and 30 seconds
#SBATCH -t 0-00:10:30

# we ask for 1 node 
#SBATCH -N 1

# we run 4 processes on each node
#SBATCH --ntasks-per-node=4

# load C compilers and MPI environment
module load 2022
module load iimpi/2022a

# EDIT THIS for your own directory
cd /home/bissstud/Students22/LisaNick/Test-mis

PMIN=4

rm -f output_bspmis
p=$PMIN
echo  "                 " >> output_bspmis
echo  "-----------------" >> output_bspmis
bsprun -n $p ./bspmis >> output_bspmis